# -*- coding: utf-8 -*-
"""3. DistilBERT for Sentiment_classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10QOe29GHtwYIDja-LthFIK0hXFcjN7gk

I use DistilBERT because it is smaller, faster, and designed for sequence classification tasks while maintaining performance close to BERT. DistilBERT is commonly used with AutoModelForSequenceClassification, and unlike BERT it does not use token_type_ids.

Required Libraries
"""

import numpy as np
import pandas as pd
import torch
import torch.nn.functional as F

from datasets import load_dataset

from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    DataCollatorWithPadding,
    TrainingArguments,
    Trainer
)

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    ConfusionMatrixDisplay,
    classification_report
)

import matplotlib.pyplot as plt

"""Load dataset"""

dataset = load_dataset("stanfordnlp/imdb")

"""load DistilBERT tokenizer"""

tokenizer = AutoTokenizer.from_pretrained(
    "distilbert-base-uncased"
)

"""Tokenize the dataset"""

def tokenize_function(examples):

    return tokenizer(
        examples["text"],
        truncation=True,
        max_length=256
    )

tokenized_dataset = dataset.map(
    tokenize_function,
    batched=True
)

"""Remove raw text column"""

tokenized_dataset = tokenized_dataset.remove_columns(["text"])

"""Rename Label Column"""

tokenized_dataset = tokenized_dataset.rename_column("label","labels")

"""Data Collator"""

data_collator = DataCollatorWithPadding(tokenizer=tokenizer)

"""Load DistilBERT Model"""

model = AutoModelForSequenceClassification.from_pretrained(
    "distilbert-base-uncased",
    num_labels=2
)

"""Define Metrics"""

def compute_metrics(eval_pred):

    logits, labels = eval_pred

    predictions = np.argmax(
        logits,
        axis=-1
    )

    return {

        "accuracy": accuracy_score(
            labels,
            predictions
        ),

        "precision": precision_score(
            labels,
            predictions
        ),

        "recall": recall_score(
            labels,
            predictions
        ),

        "f1": f1_score(
            labels,
            predictions
        )
    }

"""Training Arguments"""

training_args = TrainingArguments(

    output_dir="./distilbert_results",

    eval_strategy="epoch",

    save_strategy="epoch",

    learning_rate=2e-5,

    per_device_train_batch_size=16,

    per_device_eval_batch_size=16,

    num_train_epochs=2,

    weight_decay=0.01,

    load_best_model_at_end=True,

    report_to="none"
)

"""Create Trainer"""

trainer = Trainer(

    model=model,

    args=training_args,

    train_dataset=tokenized_dataset["train"],

    eval_dataset=tokenized_dataset["test"],

    data_collator=data_collator,

    compute_metrics=compute_metrics
)

"""Train Model"""

trainer.train()

"""Evaluate model"""

results = trainer.evaluate()
print(results)

"""Generate Predictions"""

predictions = trainer.predict(
    tokenized_dataset["test"]
)

y_pred = np.argmax(
    predictions.predictions,
    axis=1
)

y_true = predictions.label_ids

"""Classification Report"""

print(
    classification_report(
        y_true,
        y_pred,
        target_names=[
            "Negative",
            "Positive"
        ]
    )
)

"""Confusion Matrix"""

cm = confusion_matrix(
    y_true,
    y_pred
)

disp = ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=[
        "Negative",
        "Positive"
    ]
)

disp.plot()

plt.show()

"""Custom Review Testing"""

reviews = [

    "This movie was absolutely fantastic.",

    "Worst movie I have ever watched.",

    "Amazing acting and excellent story.",

    "The film was boring and too long.",

    "A masterpiece of cinema."
]

for review in reviews:

    inputs = tokenizer(
        review,
        return_tensors="pt",
        truncation=True,
        padding=True
    )

    # Move inputs to the same device as the model
    inputs = {k: v.to(model.device) for k, v in inputs.items()}

    with torch.no_grad():

        outputs = model(**inputs)

    prediction = torch.argmax(
        outputs.logits,
        dim=1
    ).item()

    label = (
        "Positive"
        if prediction == 1
        else "Negative"
    )

    print(
        f"\nReview: {review}"
    )

    print(
        f"Prediction: {label}"
    )

"""Prediction Functions"""

def predict_sentiment(text):

    inputs = tokenizer(
        text,
        return_tensors="pt",
        truncation=True,
        padding=True
    )

    # Move inputs to the same device as the model
    inputs = {k: v.to(model.device) for k, v in inputs.items()}

    with torch.no_grad():

        outputs = model(**inputs)

    probs = F.softmax(
        outputs.logits,
        dim=1
    )

    confidence, prediction = torch.max(
        probs,
        dim=1
    )

    sentiment = (
        "Positive"
        if prediction.item() == 1
        else "Negative"
    )

    return {

        "sentiment": sentiment,

        "confidence": round(
            confidence.item()*100,
            2
        )
    }

predict_sentiment(
    "This movie was brilliant and inspiring."
)