# -*- coding: utf-8 -*-
"""4. LSTM-Based Traditional Deep learning in Sentiment classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/103z2ldS53I0oV00a83UR6zBH6oCfcIWU

## Sentiment Analysis on US Airline Reviews
"""

import pandas as pd
import matplotlib.pyplot as plt
from datasets import load_dataset

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM,Dense, Dropout, SpatialDropout1D
from tensorflow.keras.layers import Embedding

"""load dataset"""

df = load_dataset("stanfordnlp/imdb")

dataset=df
# Convert train split into dataframe
train_df = pd.DataFrame(dataset["train"])

# Convert test split into dataframe
test_df = pd.DataFrame(dataset["test"])

print(train_df.head())

print(train_df.shape)
print(test_df.shape)

y_train = train_df["label"].values
y_test = test_df["label"].values

X_train = train_df["text"].values
X_test = test_df["text"].values

tokenizer = Tokenizer(
    num_words=10000,
    oov_token="<OOV>"
)

tokenizer.fit_on_texts(X_train)

vocab_size = len(tokenizer.word_index) + 1

X_train_seq = tokenizer.texts_to_sequences(
    X_train
)

X_test_seq = tokenizer.texts_to_sequences(
    X_test
)

X_train_pad = pad_sequences(
    X_train_seq,
    maxlen=250,
    padding="post",
    truncating="post"
)

X_test_pad = pad_sequences(
    X_test_seq,
    maxlen=250,
    padding="post",
    truncating="post"
)

embedding_vector_length = 32
model = Sequential()
model.add(Embedding(vocab_size, embedding_vector_length, input_length=200) )
model.add(SpatialDropout1D(0.25))
model.add(LSTM(50, dropout=0.5, recurrent_dropout=0.5))
model.add(Dropout(0.2))
model.add(Dense(1, activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam', metrics=['accuracy'])
print(model.summary())

history = model.fit(

    X_train_pad,

    y_train,

    validation_data=(
        X_test_pad,
        y_test
    ),

    epochs=5,

    batch_size=32
)

plt.plot(history.history['accuracy'], label='acc')
plt.plot(history.history['val_accuracy'], label='val_acc')
plt.legend()
plt.show()
plt.savefig("Accuracy plot.jpg")

plt.plot(history.history['loss'], label='loss')
plt.plot(history.history['val_loss'], label='val_loss')
plt.legend()
plt.show()
plt.savefig("Loss plot.jpg")

loss, accuracy = model.evaluate(
    X_test_pad,
    y_test
)

print("Test Loss :", loss)
print("Test Accuracy :", accuracy)

def predict_sentiment(text):

    seq = tokenizer.texts_to_sequences(
        [text]
    )

    padded = pad_sequences(
        seq,
        maxlen=250,
        padding="post",
        truncating="post"
    )

    prediction = model.predict(
        padded,
        verbose=0
    )[0][0]

    sentiment = (
        "Positive"
        if prediction >= 0.5
        else "Negative"
    )

    print(
        f"Sentiment: {sentiment}"
    )

    print(
        f"Confidence: {prediction:.4f}"
    )

test_sentence1 = "I enjoyed my journey on this flight."
predict_sentiment(test_sentence1)

test_sentence2 = "This is the worst flight experience of my life!"
predict_sentiment(test_sentence2)