# -*- coding: utf-8 -*-
"""Fine Tuned BERT for Sentiment_Classifier on stanfordnlp/imdb.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CUZFMevTiI3TvV-nfQpfz0VQWXbQRkpK

# Sentiment CLassifier -fine turining BERT on Movie Reviews

## Required Libraries
"""

import torch
import numpy as np
import pandas as pd
from collections import Counter

from datasets import load_dataset #to access dataset from Hugging face datassets library
from transformers import AutoTokenizer, AutoModelForSequenceClassification, TrainingArguments, Trainer
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix,ConfusionMatrixDisplay, classification_report
import matplotlib.pyplot as plt
import torch.nn.functional as F

"""### Loading the IMDB dataset"""

dataset = load_dataset("stanfordnlp/imdb")

print(dataset)

"""## Explore the Dataset

### Number of samples
"""

print("Train Size :", len(dataset["train"]))
print("Test Size :", len(dataset["test"]))
print("Unsupervised Size :", len(dataset["unsupervised"]))

"""### Features in dataset"""

dataset["train"].features

"""### View Sample reviews"""

print(dataset["train"][0]["text"])
print(dataset["train"][0]["label"])

"""### Label Mapping"""

label_names = {
    0:"Negative",
    1:"Positive"
}

print(label_names[dataset["train"][0]["label"]])

"""### Display multiple examples"""

for i in range(3):

    print(f"\nReview {i+1}")
    print("-"*60)

    print(dataset["train"][i]["text"][:500])

    print(
        "\nSentiment:",
        label_names[
            dataset["train"][i]["label"]
        ]
    )

"""### Class Distribution Analysis

Count Labels
"""

train_labels = dataset["train"]["label"]

pd.Series(train_labels).value_counts()

"""Plot Distribution"""

pd.Series(train_labels).value_counts().plot(
    kind="bar"
)

plt.title("Class Distribution")
plt.xlabel("Sentiment Label")
plt.ylabel("Count")

plt.show()

"""Percentage Distribution"""

label_counts = pd.Series(
    train_labels
).value_counts(normalize=True)*100

print(label_counts)

"""###Review Length Analysis

Calculate Lengths
"""

review_lengths = [
    len(review.split())
    for review in dataset["train"]["text"]
]

"""Basic Statistics"""

print(
    "Average Length:",
    np.mean(review_lengths)
)

print(
    "Median Length:",
    np.median(review_lengths)
)

print(
    "Maximum Length:",
    np.max(review_lengths)
)

print(
    "Minimum Length:",
    np.min(review_lengths)
)

"""Length Distribution Histogram"""

plt.figure(figsize=(10,5))

plt.hist(
    review_lengths,
    bins=50
)

plt.title(
    "Review Length Distribution"
)

plt.xlabel("Number of Words")

plt.ylabel("Frequency")

plt.show()

"""Percentile Analysis"""

print(
    "90th Percentile:",
    np.percentile(review_lengths,90)
)

print(
    "95th Percentile:",
    np.percentile(review_lengths,95)
)

print(
    "99th Percentile:",
    np.percentile(review_lengths,99)
)

"""### Vocabulary Analysis

Build Vocabulary
"""

all_words = []

for review in dataset["train"]["text"][:5000]:

    words = review.lower().split()

    all_words.extend(words)

"""Count Vocabulary"""

vocab = Counter(all_words)

print(
    "Vocabulary Size:",
    len(vocab)
)

"""Most Common Words"""

vocab.most_common(20)

"""Convert to Dataframe"""

top_words = pd.DataFrame(
    vocab.most_common(20),
    columns=["Word","Frequency"]
)

top_words

"""Visualise the most frequent words"""

top_words.plot(
    x="Word",
    y="Frequency",
    kind="bar",
    figsize=(12,5)
)

plt.title(
    "Top 20 Most Frequent Words"
)

plt.show()

"""### Review Length Categories

Most useful analysis for this report
"""

short_reviews = 0
medium_reviews = 0
long_reviews = 0

for length in review_lengths:

    if length < 100:
        short_reviews += 1

    elif length < 300:
        medium_reviews += 1

    else:
        long_reviews += 1

"""Display Counts"""

print("Short Reviews :", short_reviews)
print("Medium Reviews :", medium_reviews)
print("Long Reviews :", long_reviews)

"""Pie Chart Visualisation"""

plt.figure(figsize=(6,6))

plt.pie(
    [short_reviews,
     medium_reviews,
     long_reviews],

    labels=[
        "Short",
        "Medium",
        "Long"
    ],

    autopct="%1.1f%%"
)

plt.title(
    "Review Length Categories"
)

plt.show()

"""## Tokenization

### Load BERT tokenizer
"""

tokenizer = AutoTokenizer.from_pretrained(
    "bert-base-uncased"
)

"""### Tokenize a sample review

Inspect what BERT receives as input
"""

sample_text = dataset["train"][0]["text"]

encoded_sample = tokenizer(sample_text)

print(encoded_sample.keys())

"""### Understanding BERT inputs

Input IDs
"""

print(encoded_sample["input_ids"][:30])

"""Attention Mask"""

print(encoded_sample["attention_mask"][:30])

"""Token type IDs"""

print(encoded_sample["token_type_ids"][:30])

"""###Convert Tokens back to words"""

tokens = tokenizer.convert_ids_to_tokens(
    encoded_sample["input_ids"][:30]
)

print(tokens)

"""### Tokenize entire Dataset

Create Tokenization function
"""

def tokenize_function(examples):

    return tokenizer(
        examples["text"],
        truncation=True,
        padding="max_length",
        max_length=256
    )

"""Apply Tokenization"""

tokenized_dataset = dataset.map(
    tokenize_function,
    batched=True
)

"""### Remove Raw Text"""

tokenized_dataset = tokenized_dataset.remove_columns(
    ["text"]
)

"""###Set Pytorch Format and verify"""

tokenized_dataset.set_format(
    "torch"
)

"""## Fine-Tuning BERT

###Load Pretrained BERT Model
"""

model = AutoModelForSequenceClassification.from_pretrained(
    "bert-base-uncased",
    num_labels=2
)

"""### Create Metrics Function"""

def compute_metrics(eval_pred):

    logits, labels = eval_pred

    predictions = np.argmax(
        logits,
        axis=-1
    )

    accuracy = accuracy_score(
        labels,
        predictions
    )

    f1 = f1_score(
        labels,
        predictions
    )

    return {
        "accuracy": accuracy,
        "f1": f1
    }

"""### Training Arguments
for GPU
"""

training_args = TrainingArguments(

    output_dir="./results",

    eval_strategy="epoch",

    save_strategy="epoch",

    learning_rate=2e-5,

    per_device_train_batch_size=8,

    per_device_eval_batch_size=8,

    num_train_epochs=2,

    weight_decay=0.01,

    logging_steps=100,

    load_best_model_at_end=True,

    report_to="none"
)

"""###Create Trainer"""

trainer = Trainer(

    model=model,

    args=training_args,

    train_dataset=tokenized_dataset["train"],

    eval_dataset=tokenized_dataset["test"],

    compute_metrics=compute_metrics
)

"""### Train BERT"""

import datasets
datasets.config.TORCHVISION_AVAILABLE = False
trainer.train()

"""## Evaluation

### Evaluate Model
"""

results = trainer.evaluate()

print(results)

"""### Generate Predictions"""

predictions = trainer.predict(
    tokenized_dataset["test"]
)

"""### Predicted Labels"""

predicted_labels = np.argmax(
    predictions.predictions,
    axis=1
)

true_labels = predictions.label_ids

"""### Confusion Matrix"""

cm = confusion_matrix(
    true_labels,
    predicted_labels
)

disp = ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=[
        "Negative",
        "Positive"
    ]
)

disp.plot()

plt.show()

"""### Classification Report"""

from sklearn.metrics import classification_report

print(
    classification_report(
        true_labels,
        predicted_labels,
        target_names=[
            "Negative",
            "Positive"
        ]
    )
)

"""### Test Custom Reviews"""

custom_reviews = [

    "This movie was absolutely fantastic.",

    "The film was boring and too long.",

    "Amazing acting and excellent story.",

    "I hated every minute of it.",

    "One of the worst movies ever made."
]
for review in custom_reviews:

    inputs = tokenizer(
        review,
        return_tensors="pt",
        truncation=True,
        padding=True
    )

    # Move inputs to the same device as the model
    inputs = {key: val.to(model.device) for key, val in inputs.items()}

    outputs = model(**inputs)

    prediction = torch.argmax(
        outputs.logits,
        dim=1
    ).item()

    label = (
        "Positive"
        if prediction == 1
        else "Negative"
    )

    print(
        f"{review}\nPrediction: {label}\n"
    )

"""## Inference Functions"""

def predict(text):

    inputs = tokenizer(
        text,
        return_tensors="pt",
        truncation=True,
        padding=True
    )

    with torch.no_grad():

        outputs = model(**inputs)

    probabilities = F.softmax(
        outputs.logits,
        dim=1
    )

    confidence, prediction = torch.max(
        probabilities,
        dim=1
    )

    sentiment = (
        "Positive"
        if prediction.item() == 1
        else "Negative"
    )

    return {
        "sentiment": sentiment,
        "confidence": round(
            confidence.item()*100,
            2
        )
    }